version: 2.1
orbs:
  circleci-maven-release-orb: sonatype-nexus-community/circleci-maven-release-orb@0.0.16
references:
  workspace_root: &workspace_root
                    /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

workflows:
  version: 2.1
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
  release:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - circleci-maven-release-orb/run-maven-release:
          requires:
            - test
          ssh-fingerprints: 'a5:27:08:2f:b8:1f:69:b6:31:4a:67:25:fd:5b:53:46'


jobs:
  ##################################################################
  ##
  ##BUILD JOB
  ##
  ##################################################################
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8u141-browsers

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m



    steps:
      - checkout

      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-

      - run: mvn install -DskipTests=true -DfailIfNoTests=false

      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}


  ##################################################################
  ##
  ##TEST JOB
  ##
  ##################################################################
  test:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8u141-browsers

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m



    steps:

      - checkout

      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}-
            - maven-repo-v1-
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > /tmp/cc-test-reporter
            chmod +x /tmp/cc-test-reporter

      - run:
          name: Unit Tests
          command: mvn test

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}


      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always



      - run:
          name: Generate Jacoco results
          command:
            cd ~/repo/src/main/java &&
            /tmp/cc-test-reporter format-coverage -d --prefix ~/repo/ --add-prefix src/main/java/ -t jacoco ~/repo/target/site/jacoco/jacoco.xml

      - run:
          name: Upload Jacoco results
          command:
            cd ~/repo/src/main/java &&
            /tmp/cc-test-reporter upload-coverage -d

      - run:
          name: Upload to codeCov
          command: |
            bash <(curl -s https://codecov.io/bash) -f ~/repo/target/site/jacoco/jacoco.xml

          when: always

      - store_test_results:
          path: ~/junit

      - store_artifacts:
          path: ~/repo/target
